spring:
  application:
    name: springboot-init
  # DataSource Config
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/my_db
    username: root
    password: 196851444
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  # session expire time
  session:
    timeout: 86400
    store-type: redis
  # redis config
  redis:
    port: 6379
    host: localhost
    database: 0
server:
  port: 7529
  servlet:
    context-path: /api
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete
      logic-delete-value: 1
      logic-not-delete-value: 0